package com.erickgm.sharpsword.services;

import com.erickgm.sharpsword.domain.entities.Classe;
import com.erickgm.sharpsword.domain.entities.Habilidade;
import com.erickgm.sharpsword.domain.entities.HabilidadeClasse;
import com.erickgm.sharpsword.repository.ClasseRepository;
import com.erickgm.sharpsword.repository.HabilidadeClasseRepository;
import com.erickgm.sharpsword.repository.HabilidadeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class HabilidadeClasseService {

    @Autowired
    private HabilidadeClasseRepository habilidadeClasseRepository;

    @Autowired
    private HabilidadeRepository habilidadeRepository;

    @Autowired
    private ClasseRepository classeRepository;

    public String cargaInicial() {
        if (habilidadeClasseRepository.count() == 0)
            return cargaHabilidadesClasse();
        return "Não foi possível carregar Habilidades de Classe";
    }

    private String cargaHabilidadesClasse() {
        Classe guerreiro = classeRepository.findByNome("Guerreiro");
        Classe patrulheiro = classeRepository.findByNome("Patrulheiro");
        Classe feiticeiro = classeRepository.findByNome("Feiticeiro");
        Classe ladino = classeRepository.findByNome("Ladino");
        Classe bardo = classeRepository.findByNome("Bardo");
        Classe druida = classeRepository.findByNome("Druida");
        Classe espadachim = classeRepository.findByNome("Espadachim");
        Classe paladino = classeRepository.findByNome("Paladino");
        Classe runico = classeRepository.findByNome("Rúnico");
        Classe sacerdote = classeRepository.findByNome("Sacerdote");
        Classe xama = classeRepository.findByNome("Xamã");

        Habilidade abencoarAliados1 = habilidadeRepository.findByNome("Abençoar Aliados 1");
        Habilidade abencoarAliados2 = habilidadeRepository.findByNome("Abençoar Aliados 2");
        Habilidade abencoarObjeto = habilidadeRepository.findByNome("Abençoar Objeto");
        Habilidade acrobata = habilidadeRepository.findByNome("Acrobata");
        Habilidade anularGolpe = habilidadeRepository.findByNome("Anular Golpe");
        Habilidade aparar = habilidadeRepository.findByNome("Aparar");
        Habilidade apararMagia = habilidadeRepository.findByNome("Aparar Magia");
        Habilidade aptidaoElemental = habilidadeRepository.findByNome("Aptidão Elemental");
        Habilidade arcoVoltaico = habilidadeRepository.findByNome("Arco Voltaico");
        Habilidade arieteMagico = habilidadeRepository.findByNome("Aríete Mágico");
        Habilidade armaFiel = habilidadeRepository.findByNome("Arma Fiel");
        Habilidade armaGelida = habilidadeRepository.findByNome("Arma Gélida");
        Habilidade armaIncandescente = habilidadeRepository.findByNome("Arma Incandescente");
        Habilidade armaRelampejante = habilidadeRepository.findByNome("Arma Relampejante");
        Habilidade armadilheiro = habilidadeRepository.findByNome("Armadilheiro");
        Habilidade armaduraFiel = habilidadeRepository.findByNome("Armadura Fiel");
        Habilidade arqueria = habilidadeRepository.findByNome("Arqueria");
        Habilidade arqueriaDeMestre = habilidadeRepository.findByNome("Arqueria de Mestre");
        Habilidade asasCelestiais = habilidadeRepository.findByNome("Asas Celestiais");
        Habilidade asceta = habilidadeRepository.findByNome("Asceta");
        Habilidade ataqueAleijador = habilidadeRepository.findByNome("Ataque Aleijador");
        Habilidade ataqueChocante = habilidadeRepository.findByNome("Ataque Chocante");
        Habilidade ataqueCongelante = habilidadeRepository.findByNome("Ataque Congelante");
        Habilidade ataqueDoBufalo = habilidadeRepository.findByNome("Ataque do Búfalo");
        Habilidade ataqueEvasivo = habilidadeRepository.findByNome("Ataque Evasivo");
        Habilidade ataqueFantasma = habilidadeRepository.findByNome("Ataque Fantasma");
        Habilidade ataqueFlamejante = habilidadeRepository.findByNome("Ataque Flamejante");
        Habilidade ataqueGiratorio = habilidadeRepository.findByNome("Ataque Giratório");
        Habilidade ataqueRedirecionado = habilidadeRepository.findByNome("Ataque Redirecionado");
        Habilidade ataqueSimultaneo = habilidadeRepository.findByNome("Ataque Simultâneo");
        Habilidade auradeCura1 = habilidadeRepository.findByNome("Aura de Cura 1");
        Habilidade auradeCura2 = habilidadeRepository.findByNome("Aura de Cura 2");
        Habilidade austeridade = habilidadeRepository.findByNome("Austeridade");
        Habilidade banir = habilidadeRepository.findByNome("Banir");
        Habilidade bencaodeEllenis = habilidadeRepository.findByNome("Benção de Ellenis");
        Habilidade bestializar = habilidadeRepository.findByNome("Bestializar");
        Habilidade bolaDeFogo = habilidadeRepository.findByNome("Bola de Fogo");
        Habilidade bonsFrutos = habilidadeRepository.findByNome("Bons Frutos");
        Habilidade bravuraSelvagem1 = habilidadeRepository.findByNome("Bravura Selvagem 1");
        Habilidade brigao = habilidadeRepository.findByNome("Brigão");
        Habilidade cacadorDeCriatura = habilidadeRepository.findByNome("Caçador de [Criatura]");
        Habilidade cacadorDeMonstro = habilidadeRepository.findByNome("Caçador de [Monstro]");
        Habilidade caminhadaMagica = habilidadeRepository.findByNome("Caminhada Mágica");
        Habilidade camuflagem = habilidadeRepository.findByNome("Camuflagem");
        Habilidade cancaoDaProvocacao = habilidadeRepository.findByNome("Canção da Provocação");
        Habilidade cancaoDesesperadora = habilidadeRepository.findByNome("Canção Desesperadora");
        Habilidade cancaoDaSereia = habilidadeRepository.findByNome("Canção da Sereia");
        Habilidade cancaoDesconcentrante = habilidadeRepository.findByNome("Canção Desconcentrante");
        Habilidade cancaoDoRequiem = habilidadeRepository.findByNome("Canção do Réquiem");
        Habilidade cancaoDoTriunfo = habilidadeRepository.findByNome("Canção do Triunfo");
        Habilidade cancaoExultante = habilidadeRepository.findByNome("Canção Exultante");
        Habilidade cariatide = habilidadeRepository.findByNome("Cariátide");
        Habilidade cavaleiroExperiente = habilidadeRepository.findByNome("Cavaleiro Experiente");
        Habilidade chuvaDeFlechas = habilidadeRepository.findByNome("Chuva de Flechas");
        Habilidade chuvaDeFlechas2 = habilidadeRepository.findByNome("Chuva de Flechas 2");
        Habilidade circulodaProtecao = habilidadeRepository.findByNome("Círculo da Proteção");
        Habilidade codigoDaCoragem = habilidadeRepository.findByNome("Código da Coragem");
        Habilidade codigoDaCortesia = habilidadeRepository.findByNome("Código da Cortesia");
        Habilidade codigoDaHonestidade = habilidadeRepository.findByNome("Código da Honestidade");
        Habilidade codigoDaJustica = habilidadeRepository.findByNome("Código da Justiça");
        Habilidade codigoDaLealdade = habilidadeRepository.findByNome("Código da Lealdade");
        Habilidade comandoHeroico = habilidadeRepository.findByNome("Comando Heroico");
        Habilidade combatecomDuasArmas1 = habilidadeRepository.findByNome("Combate com Duas Armas 1");
        Habilidade combatecomDuasArmas2 = habilidadeRepository.findByNome("Combate com Duas Armas 2");
        Habilidade combateEmGrupo = habilidadeRepository.findByNome("Combate em Grupo");
        Habilidade combateMontado = habilidadeRepository.findByNome("Combate Montado");
        Habilidade combatePesado = habilidadeRepository.findByNome("Combate Pesado");
        Habilidade combateTatico = habilidadeRepository.findByNome("Combate Tático");
        Habilidade companheiroAnimal1 = habilidadeRepository.findByNome("Companheiro Animal 1");
        Habilidade companheiroAnimal2 = habilidadeRepository.findByNome("Companheiro Animal 2");
        Habilidade companheiroAnimal3 = habilidadeRepository.findByNome("Companheiro Animal 3");
        Habilidade comunhaoComEspiritos = habilidadeRepository.findByNome("Comunhão com Espíritos");
        Habilidade congelar = habilidadeRepository.findByNome("Congelar");
        Habilidade conhecimentoArcano = habilidadeRepository.findByNome("Conhecimento Arcano");
        Habilidade conhecimentoMistico = habilidadeRepository.findByNome("Conhecimento Místico");
        Habilidade conjurarAbrigo = habilidadeRepository.findByNome("Conjurar Abrigo");
        Habilidade conjurarArmadosDeuses = habilidadeRepository.findByNome("Conjurar Arma dos Deuses");
        Habilidade conjurarBroquelMistico = habilidadeRepository.findByNome("Conjurar Broquel Místico");
        Habilidade conjurarEscudo = habilidadeRepository.findByNome("Conjurar Escudo");
        Habilidade conjurarFalangedoDestino = habilidadeRepository.findByNome("Conjurar Falange do Destino");
        Habilidade conjurarLancadoDestino = habilidadeRepository.findByNome("Conjurar Lança do Destino");
        Habilidade contatoComEspiritos = habilidadeRepository.findByNome("Contato com Espíritos");
        Habilidade contatosNoCrime = habilidadeRepository.findByNome("Contatos no Crime");
        Habilidade convocarAnimais = habilidadeRepository.findByNome("Convocar Animais");
        Habilidade coracaodaBatalha = habilidadeRepository.findByNome("Coração da Batalha");
        Habilidade corpoFechado = habilidadeRepository.findByNome("Corpo Fechado");
        Habilidade corteArterial = habilidadeRepository.findByNome("Corte Arterial");
        Habilidade criarGolem = habilidadeRepository.findByNome("Criar Golem");
        Habilidade curarFerimentos1 = habilidadeRepository.findByNome("Curar Ferimentos 1");
        Habilidade curarFerimentos2 = habilidadeRepository.findByNome("Curar Ferimentos 2");
        Habilidade dancaDasEspadas1 = habilidadeRepository.findByNome("Dança das Espadas 1");
        Habilidade dancaDasEspadas2 = habilidadeRepository.findByNome("Dança das Espadas 2");
        Habilidade decapitar = habilidadeRepository.findByNome("Decapitar");
        Habilidade defesaAgressiva = habilidadeRepository.findByNome("Defesa Agressiva");
        Habilidade defletor = habilidadeRepository.findByNome("Defletor");
        Habilidade desarmarOponente = habilidadeRepository.findByNome("Desarmar Oponente");
        Habilidade desativarItem = habilidadeRepository.findByNome("Desativar Item");
        Habilidade despertarAFlora = habilidadeRepository.findByNome("Despertar a Flora");
        Habilidade destemor = habilidadeRepository.findByNome("Destemor");
        Habilidade destruicaoElemental = habilidadeRepository.findByNome("Destruição Elemental");
        Habilidade detectarMagia = habilidadeRepository.findByNome("Detectar Magia");
        Habilidade disparoCerteiro = habilidadeRepository.findByNome("Disparo Certeiro");
        Habilidade disparoForte = habilidadeRepository.findByNome("Disparo Forte");
        Habilidade dissiparMagia = habilidadeRepository.findByNome("Dissipar Magia");
        Habilidade dogma = habilidadeRepository.findByNome("Dogma");
        Habilidade egide = habilidadeRepository.findByNome("Égide");
        Habilidade eletricidadeEstatica = habilidadeRepository.findByNome("Eletricidade Estática");
        Habilidade eletrosfera = habilidadeRepository.findByNome("Eletrosfera");
        Habilidade eloquente = habilidadeRepository.findByNome("Eloquente");
        Habilidade emboscar = habilidadeRepository.findByNome("Emboscar");
        Habilidade empalar = habilidadeRepository.findByNome("Empalar");
        Habilidade enPassant = habilidadeRepository.findByNome("En Passant");
        Habilidade enfeiticarArma1 = habilidadeRepository.findByNome("Enfeitiçar Arma 1");
        Habilidade enfeiticarArma2 = habilidadeRepository.findByNome("Enfeitiçar Arma 2");
        Habilidade enfeiticarArmadura = habilidadeRepository.findByNome("Enfeitiçar Armadura");
        Habilidade entrelacar = habilidadeRepository.findByNome("Entrelaçar");
        Habilidade espiritoAnimal = habilidadeRepository.findByNome("Espírito Animal");
        Habilidade estabilidade = habilidadeRepository.findByNome("Estabilidade");
        Habilidade evasao = habilidadeRepository.findByNome("Evasão");
        Habilidade evocarNevasca = habilidadeRepository.findByNome("Evocar Nevasca");
        Habilidade evocarTemporal = habilidadeRepository.findByNome("Evocar Temporal");
        Habilidade exorcismo = habilidadeRepository.findByNome("Exorcismo");
        Habilidade explorarSurpresa = habilidadeRepository.findByNome("Explorar Surpresa");
        Habilidade falhasdaArmadura = habilidadeRepository.findByNome("Falhas da Armadura");
        Habilidade flanquear = habilidadeRepository.findByNome("Flanquear");
        Habilidade flechasRapidas = habilidadeRepository.findByNome("Flechas Rápidas");
        Habilidade flexivel = habilidadeRepository.findByNome("Flexível");
        Habilidade forcaDeExplosao = habilidadeRepository.findByNome("Força de Explosão");
        Habilidade frutoRevigorante = habilidadeRepository.findByNome("Fruto Revigorante");
        Habilidade furtivo = habilidadeRepository.findByNome("Furtivo");
        Habilidade gatuno = habilidadeRepository.findByNome("Gatuno");
        Habilidade gavinhasEEspinhos = habilidadeRepository.findByNome("Gavinhas e Espinhos");
        Habilidade golpeComEscudo = habilidadeRepository.findByNome("Golpe com Escudo");
        Habilidade golpeDevastador1 = habilidadeRepository.findByNome("Golpe Devastador 1");
        Habilidade golpeDevastador2 = habilidadeRepository.findByNome("Golpe Devastador 2");
        Habilidade golpeDoVento = habilidadeRepository.findByNome("Golpe do Vento");
        Habilidade golpesRapidos = habilidadeRepository.findByNome("Golpes Rápidos");
        Habilidade gracaDivina = habilidadeRepository.findByNome("Graça Divina");
        Habilidade gregario = habilidadeRepository.findByNome("Gregário");
        Habilidade gritoDeGuerra1 = habilidadeRepository.findByNome("Grito de Guerra 1");
        Habilidade gritoDeGuerra2 = habilidadeRepository.findByNome("Grito de Guerra 2");
        Habilidade gritoDeIntimidacao = habilidadeRepository.findByNome("Grito de Intimidação");
        Habilidade gritoEnsurdecedor = habilidadeRepository.findByNome("Grito Ensurdecedor");
        Habilidade gritoEstilhacador = habilidadeRepository.findByNome("Grito Estilhaçador");
        Habilidade guerreiroDeAco1 = habilidadeRepository.findByNome("Guerreiro de Aço 1");
        Habilidade guerreiroDeAco2 = habilidadeRepository.findByNome("Guerreiro de Aço 2");
        Habilidade guiaEspiritual = habilidadeRepository.findByNome("Guia Espiritual");
        Habilidade herbalismo = habilidadeRepository.findByNome("Herbalismo");
        Habilidade hierofante = habilidadeRepository.findByNome("Hierofante");
        Habilidade implacavel = habilidadeRepository.findByNome("Implacável");
        Habilidade improvisacaoLadina = habilidadeRepository.findByNome("Improvisação Ladina");
        Habilidade incandescer = habilidadeRepository.findByNome("Incandescer");
        Habilidade inferno = habilidadeRepository.findByNome("Inferno");
        Habilidade inflamar = habilidadeRepository.findByNome("Inflamar");
        Habilidade infravisao = habilidadeRepository.findByNome("Infravisão");
        Habilidade integridade = habilidadeRepository.findByNome("Integridade");
        Habilidade investidaForte = habilidadeRepository.findByNome("Investida Forte");
        Habilidade investidaMortal = habilidadeRepository.findByNome("Investida Mortal");
        Habilidade invocarElemental1 = habilidadeRepository.findByNome("Invocar Elemental 1");
        Habilidade invocarElemental2 = habilidadeRepository.findByNome("Invocar Elemental 2");
        Habilidade invocarElemental3 = habilidadeRepository.findByNome("Invocar Elemental 3");
        Habilidade justicaFinal1 = habilidadeRepository.findByNome("Justiça Final 1");
        Habilidade justicaFinal2 = habilidadeRepository.findByNome("Justiça Final 2");
        Habilidade levitar = habilidadeRepository.findByNome("Levitar");
        Habilidade linguaAfiada = habilidadeRepository.findByNome("Língua Afiada");
        Habilidade maestriaElemental = habilidadeRepository.findByNome("Maestria Elemental");
        Habilidade malabarista = habilidadeRepository.findByNome("Malabarista");
        Habilidade manterGolem = habilidadeRepository.findByNome("Manter Golem");
        Habilidade mantoCrepitante = habilidadeRepository.findByNome("Manto Crepitante");
        Habilidade matadordeCriatura = habilidadeRepository.findByNome("Matador de [Criatura]");
        Habilidade melodiaDaFuria = habilidadeRepository.findByNome("Melodia da Fúria");
        Habilidade melodiaDancante = habilidadeRepository.findByNome("Melodia Dançante");
        Habilidade melodiaDoEnjoo = habilidadeRepository.findByNome("Melodia do Enjoo");
        Habilidade melodiaDoRepouso = habilidadeRepository.findByNome("Melodia do Repouso");
        Habilidade melodiaDosAnimais = habilidadeRepository.findByNome("Melodia dos Animais");
        Habilidade melodiaSonifera = habilidadeRepository.findByNome("Melodia Sonífera");
        Habilidade menteDisciplinada = habilidadeRepository.findByNome("Mente Disciplinada");
        Habilidade mestreDasAdagas1 = habilidadeRepository.findByNome("Mestre das Adagas 1");
        Habilidade mestreDasAdagas2 = habilidadeRepository.findByNome("Mestre das Adagas 2");
        Habilidade mestreDasAdagas3 = habilidadeRepository.findByNome("Mestre das Adagas 3");
        Habilidade mestreDasNotas = habilidadeRepository.findByNome("Mestre das Notas");
        Habilidade mestreDeArmas1 = habilidadeRepository.findByNome("Mestre de Armas 1");
        Habilidade mestredeArmas2 = habilidadeRepository.findByNome("Mestre de Armas 2");
        Habilidade mestredeArmas3 = habilidadeRepository.findByNome("Mestre de Armas 3");
        Habilidade mestreEspecialista = habilidadeRepository.findByNome("Mestre Especialista");
        Habilidade montariaEspecial1 = habilidadeRepository.findByNome("Montaria Especial 1");
        Habilidade montariaEspecial2 = habilidadeRepository.findByNome("Montaria Especial 2");
        Habilidade montariaEspecial3 = habilidadeRepository.findByNome("Montaria Especial 3");
        Habilidade motivar = habilidadeRepository.findByNome("Motivar");
        Habilidade moverTerra = habilidadeRepository.findByNome("Mover Terra");
        Habilidade movimentosEvasivos = habilidadeRepository.findByNome("Movimentos Evasivos");
        Habilidade nocautear = habilidadeRepository.findByNome("Nocautear");
        Habilidade olhoDaAguia = habilidadeRepository.findByNome("Olho da Águia");
        Habilidade olhoDoFuracao = habilidadeRepository.findByNome("Olho do Furacão");
        Habilidade ondaDeChamas = habilidadeRepository.findByNome("Onda de Chamas");
        Habilidade ondaDeFrio = habilidadeRepository.findByNome("Onda de Frio");
        Habilidade ondaDeRaios = habilidadeRepository.findByNome("Onda de Raios");
        Habilidade ondaFantasma = habilidadeRepository.findByNome("Onda Fantasma");
        Habilidade orbeDeContencao = habilidadeRepository.findByNome("Orbe de Contenção");
        Habilidade panache = habilidadeRepository.findByNome("Panache");
        Habilidade paredeDeEscudos = habilidadeRepository.findByNome("Parede de Escudos");
        Habilidade paredeDeGelo = habilidadeRepository.findByNome("Parede de Gelo");
        Habilidade passoLeve = habilidadeRepository.findByNome("Passo Leve");
        Habilidade poesiaDosBardos = habilidadeRepository.findByNome("Poesia dos Bardos");
        Habilidade pontifice = habilidadeRepository.findByNome("Pontífice");
        Habilidade portal = habilidadeRepository.findByNome("Portal");
        Habilidade precisao = habilidadeRepository.findByNome("Precisão");
        Habilidade primaz = habilidadeRepository.findByNome("Primaz");
        Habilidade principioNatural = habilidadeRepository.findByNome("Princípio Natural");
        Habilidade prisaoDeGelo = habilidadeRepository.findByNome("Prisão de Gelo");
        Habilidade protecaoMistica = habilidadeRepository.findByNome("Proteção Mística");
        Habilidade punhoDePedra = habilidadeRepository.findByNome("Punho de Pedra");
        Habilidade purgar = habilidadeRepository.findByNome("Purgar");
        Habilidade rajadaDeAgua = habilidadeRepository.findByNome("Rajada de Água");
        Habilidade rajadaDeEspinhos = habilidadeRepository.findByNome("Rajada de Espinhos");
        Habilidade rajadaDeGelo = habilidadeRepository.findByNome("Rajada de Gelo");
        Habilidade rajadaElemental = habilidadeRepository.findByNome("Rajada Elemental");
        Habilidade relampago1 = habilidadeRepository.findByNome("Relâmpago 1");
        Habilidade relampago2 = habilidadeRepository.findByNome("Relâmpago 2");
        Habilidade resistenciaElemental = habilidadeRepository.findByNome("Resistência Elemental");
        Habilidade retalhar = habilidadeRepository.findByNome("Retalhar");
        Habilidade retesarEficiente = habilidadeRepository.findByNome("Retesar Eficiente");
        Habilidade ripostar = habilidadeRepository.findByNome("Ripostar");
        Habilidade sabedoriaSelvagem = habilidadeRepository.findByNome("Sabedoria Selvagem");
        Habilidade semEscapatoria = habilidadeRepository.findByNome("Sem Escapatória");
        Habilidade senhorDasLaminas = habilidadeRepository.findByNome("Senhor das Lâminas");
        Habilidade telecinesia = habilidadeRepository.findByNome("Telecinésia");
        Habilidade teleporte1 = habilidadeRepository.findByNome("Teleporte 1");
        Habilidade teleporte2 = habilidadeRepository.findByNome("Teleporte 2");
        Habilidade tempestadeDeGelo = habilidadeRepository.findByNome("Tempestade de Gelo");
        Habilidade tempestadeDeLaminas = habilidadeRepository.findByNome("Tempestade de Lâminas");
        Habilidade toqueMistico = habilidadeRepository.findByNome("Toque Místico");
        Habilidade touche = habilidadeRepository.findByNome("Touché");
        Habilidade transpor = habilidadeRepository.findByNome("Transpor");
        Habilidade trapaceiroImpecavel = habilidadeRepository.findByNome("Trapaceiro Impecável");
        Habilidade truqueSujo = habilidadeRepository.findByNome("Truque Sujo");
        Habilidade turbilhao = habilidadeRepository.findByNome("Turbilhão");
        Habilidade valordaVitoria = habilidadeRepository.findByNome("Valor da Vitória");
        Habilidade velocidade = habilidadeRepository.findByNome("Velocidade");
        Habilidade veneficio = habilidadeRepository.findByNome("Venefício");
        Habilidade virtuoso = habilidadeRepository.findByNome("Virtuoso");
        Habilidade vocalista = habilidadeRepository.findByNome("Vocalista");
        Habilidade chamadodoAlfa = habilidadeRepository.findByNome("Chamado do Alfa");
        Habilidade curaEspiritual = habilidadeRepository.findByNome("Cura Espiritual");
        Habilidade formaAnimal1 = habilidadeRepository.findByNome("Forma Animal 1");
        Habilidade invocarEspiritoAnimal = habilidadeRepository.findByNome("Invocar Espírito Animal");
        Habilidade rugidodoAlfa = habilidadeRepository.findByNome("Rugido do Alfa");
        Habilidade rugidodoPredador = habilidadeRepository.findByNome("Rugido do Predador");
        Habilidade vantagemAnimal1 = habilidadeRepository.findByNome("Vantagem Animal 1");
        Habilidade atropelar = habilidadeRepository.findByNome("Atropelar");
        Habilidade caminhadaFantasma = habilidadeRepository.findByNome("Caminhada Fantasma");
        Habilidade companheiroEspiritual = habilidadeRepository.findByNome("Companheiro Espiritual");
        Habilidade estracalhar = habilidadeRepository.findByNome("Estraçalhar");
        Habilidade formaAnimal2 = habilidadeRepository.findByNome("Forma Animal 2");
        Habilidade imunidadeEspiritual = habilidadeRepository.findByNome("Imunidade Espiritual");
        Habilidade mestreDomador = habilidadeRepository.findByNome("Mestre Domador");
        Habilidade vantagemAnimal2 = habilidadeRepository.findByNome("Vantagem Animal 2");
        Habilidade guardiaoDaNatureza = habilidadeRepository.findByNome("Guardião da Natureza");

        // Todas as classes
        /*
        List<Classe> todasClasses = new ArrayList<>();
        todasClasses.add(guerreiro);
        todasClasses.add(patrulheiro);
        todasClasses.add(feiticeiro);
        todasClasses.add(ladino);
        todasClasses.add(bardo);
        todasClasses.add(druida);
        todasClasses.add(espadachim);
        todasClasses.add(paladino);
        todasClasses.add(runico);
        todasClasses.add(sacerdote);
        todasClasses.add(xama);

        for (Classe classe: todasClasses) {
            habilidadeClasseRepository.save(new HabilidadeClasse(agilidadeHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(atletismo, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(forcaHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(forcaInterior, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(inteligenciaHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(nanismo, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(nervosdeAco, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(recursos, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(vontadeDeFerro, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(vontadeHeroica, classe, false));
        }
        */

        // Bardos
        habilidadeClasseRepository.save(new HabilidadeClasse(poesiaDosBardos, bardo, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(aparar, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueRedirecionado, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDaProvocacao, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDesesperadora, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDoTriunfo, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoExultante, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(eloquente, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evasao, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(furtivo, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gregario, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra1, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoEnsurdecedor, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoEstilhacador, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(linguaAfiada, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(malabarista, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaDancante, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaDoEnjoo, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaDoRepouso, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaSonifera, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDasNotas, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(truqueSujo, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDaSereia, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDesconcentrante, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(coracaodaBatalha, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra2, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeIntimidacao, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaDaFuria, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(melodiaDosAnimais, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(trapaceiroImpecavel, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(virtuoso, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(vocalista, bardo, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cancaoDoRequiem, bardo, false));

        // Druidas
        habilidadeClasseRepository.save(new HabilidadeClasse(conhecimentoMistico, druida, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(apararMagia, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(asasCelestiais, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bencaodeEllenis, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bestializar, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bonsFrutos, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(caminhadaMagica, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal1, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal2, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(convocarAnimais, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(detectarMagia, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(entrelacar, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(espiritoAnimal, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evocarTemporal, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(frutoRevigorante, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(herbalismo, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(moverTerra, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(principioNatural, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rajadaDeAgua, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rajadaDeEspinhos, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(sabedoriaSelvagem, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(turbilhao, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal3, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarAbrigo, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(despertarAFlora, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dissiparMagia, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evocarNevasca, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gavinhasEEspinhos, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(olhoDoFuracao, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(orbeDeContencao, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(punhoDePedra, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(veneficio, druida, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(hierofante, druida, false));

        // Espadachins
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDeArmas1, espadachim, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(acrobata, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(aparar, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueAleijador, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueGiratorio, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueRedirecionado, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas1, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateTatico, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(corteArterial, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dancaDasEspadas1, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(desarmarOponente, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(eloquente, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evasao, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(falhasdaArmadura, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpesRapidos, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(investidaMortal, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(linguaAfiada, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(movimentosEvasivos, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(panache, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(semEscapatoria, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(touche, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(truqueSujo, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas2, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(coracaodaBatalha, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dancaDasEspadas2, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(decapitar, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(implacavel, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestredeArmas2, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(retalhar, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ripostar, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(tempestadeDeLaminas, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(valordaVitoria, espadachim, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(senhorDasLaminas, espadachim, false));

        // Feiticeiros
        habilidadeClasseRepository.save(new HabilidadeClasse(conhecimentoArcano, feiticeiro, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(apararMagia, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(arcoVoltaico, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(arieteMagico, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bolaDeFogo, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(congelar, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(detectarMagia, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(eletricidadeEstatica, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(inflamar, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(infravisao, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(invocarElemental1, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(invocarElemental2, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(levitar, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mantoCrepitante, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(menteDisciplinada, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(paredeDeGelo, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rajadaDeGelo, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(relampago1, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rajadaElemental, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(resistenciaElemental, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(telecinesia, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(teleporte1, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(aptidaoElemental, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dissiparMagia, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(eletrosfera, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(incandescer, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(inferno, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(invocarElemental3, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(prisaoDeGelo, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(relampago2, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(teleporte2, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(tempestadeDeGelo, feiticeiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(maestriaElemental, feiticeiro, false));

        // Guerreiros
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDeArmas1, guerreiro, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(anularGolpe, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueDoBufalo, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueGiratorio, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueSimultaneo, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(brigao, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateEmGrupo, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas1, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatePesado, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateTatico, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(defesaAgressiva, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(defletor, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(estabilidade, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpeDevastador1, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpeComEscudo, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra1, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco1, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(investidaMortal, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(nocautear, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(paredeDeEscudos, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(semEscapatoria, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(transpor, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas2, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(forcaDeExplosao, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpeDevastador2, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra2, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeIntimidacao, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco2, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(implacavel, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(investidaForte, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestredeArmas2, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(valordaVitoria, guerreiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestredeArmas3, guerreiro, false));

        // Ladinos
        habilidadeClasseRepository.save(new HabilidadeClasse(gatuno, ladino, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(acrobata, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(aparar, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armadilheiro, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueAleijador, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueEvasivo, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueRedirecionado, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas1, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(contatosNoCrime, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(corteArterial, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(eloquente, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evasao, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(falhasdaArmadura, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(flanquear, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(flexivel, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(furtivo, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpesRapidos, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDasAdagas1, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDasAdagas2, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(movimentosEvasivos, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(malabarista, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(truqueSujo, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(camuflagem, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas2, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(emboscar, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(enPassant, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(explorarSurpresa, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(improvisacaoLadina, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDasAdagas3, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(passoLeve, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ripostar, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(trapaceiroImpecavel, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreEspecialista, ladino, false));

        // Paladinos
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDeArmas1, paladino, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(austeridade, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cavaleiroExperiente, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(codigoDaCoragem, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(codigoDaCortesia, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(codigoDaHonestidade, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(codigoDaJustica, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(codigoDaLealdade, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateMontado, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateTatico, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(defletor, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(egide, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(estabilidade, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra1, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco1, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(justicaFinal1, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(montariaEspecial1, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(montariaEspecial2, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(motivar, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(nocautear, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(paredeDeEscudos, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(semEscapatoria, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(banir, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(comandoHeroico, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(coracaodaBatalha, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(destemor, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gritoDeGuerra2, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco2, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(implacavel, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(justicaFinal2, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(montariaEspecial3, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(valordaVitoria, paladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(integridade, paladino, false));

        // Patrulheiros
        habilidadeClasseRepository.save(new HabilidadeClasse(arqueria, patrulheiro, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(acrobata, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armadilheiro, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueAleijador, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bencaodeEllenis, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cacadorDeCriatura, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(chuvaDeFlechas, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal1, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal2, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(disparoForte, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(disparoCerteiro, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(espiritoAnimal, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(evasao, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(falhasdaArmadura, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(flechasRapidas, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(furtivo, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(herbalismo, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(precisao, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(retesarEficiente, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(sabedoriaSelvagem, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(truqueSujo, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cacadorDeMonstro, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(camuflagem, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(chuvaDeFlechas2, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal3, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(emboscar, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(empalar, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(matadordeCriatura, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(olhoDaAguia, patrulheiro, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(passoLeve, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(veneficio, ladino, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(arqueriaDeMestre, patrulheiro, false));

        // Rúnicos
        habilidadeClasseRepository.save(new HabilidadeClasse(conhecimentoArcano, runico, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(apararMagia, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armaFiel, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armaIncandescente, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armaGelida, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armaRelampejante, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(armaduraFiel, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueFantasma, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateTatico, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarEscudo, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(desativarItem, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(detectarMagia, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(enfeiticarArma1, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(enfeiticarArmadura, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco1, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(menteDisciplinada, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ondaDeChamas, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ondaDeFrio, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ondaDeRaios, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ondaFantasma, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(resistenciaElemental, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(semEscapatoria, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(aptidaoElemental, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueChocante, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueCongelante, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueFlamejante, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(golpeDoVento, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dissiparMagia, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(enfeiticarArma2, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guerreiroDeAco2, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(implacavel, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestredeArmas2, runico, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(destruicaoElemental, runico, false));

        // Sacerdotes
        habilidadeClasseRepository.save(new HabilidadeClasse(conhecimentoMistico, sacerdote, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(abencoarAliados1, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(abencoarObjeto, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(apararMagia, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(asasCelestiais, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(asceta, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(auradeCura1, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(caminhadaMagica, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(cariatide, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarArmadosDeuses, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarLancadoDestino, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarBroquelMistico, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(corpoFechado, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(curarFerimentos1, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(detectarMagia, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dogma, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(exorcismo, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(gracaDivina, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(protecaoMistica, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(purgar, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(toqueMistico, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(velocidade, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(abencoarAliados2, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(auradeCura2, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(circulodaProtecao, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(conjurarFalangedoDestino, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(criarGolem, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(curarFerimentos2, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(dissiparMagia, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(manterGolem, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(portal, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(primaz, sacerdote, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(pontifice, sacerdote, false));


        // Xamãs
        habilidadeClasseRepository.save(new HabilidadeClasse(guiaEspiritual, xama, true));
        habilidadeClasseRepository.save(new HabilidadeClasse(ataqueDoBufalo, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bencaodeEllenis, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(brigao, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(bravuraSelvagem1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combateTatico, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal2, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(comunhaoComEspiritos, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(contatoComEspiritos, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(chamadodoAlfa, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(combatecomDuasArmas1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(curaEspiritual, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(espiritoAnimal, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(formaAnimal1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(herbalismo, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(invocarEspiritoAnimal, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rugidodoAlfa, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(rugidodoPredador, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(sabedoriaSelvagem, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(semEscapatoria, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(vantagemAnimal1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(atropelar, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(caminhadaFantasma, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroAnimal3, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(companheiroEspiritual, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(estracalhar, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(formaAnimal2, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(implacavel, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(imunidadeEspiritual, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(mestreDomador, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(vantagemAnimal2, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(guardiaoDaNatureza, xama, false));

        return "Habilidades de Classe carregadas";
    }

    public HabilidadeClasse obterHabilidadeClassePeloId(long id) {
        return habilidadeClasseRepository.findById(id);
    }
}
