package com.erickgm.sharpsword.services;

import com.erickgm.sharpsword.domain.entities.Classe;
import com.erickgm.sharpsword.domain.entities.Habilidade;
import com.erickgm.sharpsword.domain.entities.HabilidadeClasse;
import com.erickgm.sharpsword.domain.entities.HabilidadeRaca;
import com.erickgm.sharpsword.repository.ClasseRepository;
import com.erickgm.sharpsword.repository.HabilidadeClasseRepository;
import com.erickgm.sharpsword.repository.HabilidadeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class HabilidadeClasseService {

    @Autowired
    private HabilidadeClasseRepository habilidadeClasseRepository;

    @Autowired
    private HabilidadeRepository habilidadeRepository;

    @Autowired
    private ClasseRepository classeRepository;

    public String cargaInicial() {
        if (habilidadeClasseRepository.count() == 0)
            return cargaHabilidadesClasse();
        return "Não foi possível carregar Habilidades de Classe";
    }

    private String cargaHabilidadesClasse() {
        Classe guerreiro = classeRepository.findByNome("Guerreiro");
        Classe patrulheiro = classeRepository.findByNome("Patrulheiro");
        Classe feiticeiro = classeRepository.findByNome("Feiticeiro");
        Classe ladino = classeRepository.findByNome("Ladino");
        Classe bardo = classeRepository.findByNome("Bardo");
        Classe druida = classeRepository.findByNome("Druida");
        Classe espadachim = classeRepository.findByNome("Espadachim");
        Classe paladino = classeRepository.findByNome("Paladino");
        Classe runico = classeRepository.findByNome("Rúnico");
        Classe sacerdote = classeRepository.findByNome("Sacerdote");
        Classe xama = classeRepository.findByNome("Xamã");

        Habilidade abencoarAliados1 = habilidadeRepository.findByNome("Abençoar Aliados 1");
        Habilidade abencoarAliados2 = habilidadeRepository.findByNome("Abençoar Aliados 2");
        Habilidade abencoarObjeto = habilidadeRepository.findByNome("Abençoar Objeto");
        Habilidade abracodePedra = habilidadeRepository.findByNome("Abraço de Pedra");
        Habilidade acrobata = habilidadeRepository.findByNome("Acrobata");
        Habilidade adaptabilidade = habilidadeRepository.findByNome("Adaptabilidade");
        Habilidade agilidadeHeroica = habilidadeRepository.findByNome("Agilidade Heróica");
        Habilidade anularGolpe = habilidadeRepository.findByNome("Anular Golpe");
        Habilidade aparar = habilidadeRepository.findByNome("Aparar");
        Habilidade apararMagia = habilidadeRepository.findByNome("Aparar Magia");
        Habilidade aptidaoElemental = habilidadeRepository.findByNome("Aptidão Elemental");
        Habilidade arboricola = habilidadeRepository.findByNome("Arborícola");
        Habilidade arcoVoltaico = habilidadeRepository.findByNome("Arco Voltaico");
        Habilidade arieteMagico = habilidadeRepository.findByNome("Aríete Mágico");
        Habilidade armaFiel = habilidadeRepository.findByNome("Arma Fiel");
        Habilidade armaGelida = habilidadeRepository.findByNome("Arma Gélida");
        Habilidade armaIncandescente = habilidadeRepository.findByNome("Arma Incandescente");
        Habilidade armaRelampejante = habilidadeRepository.findByNome("Arma Relampejante");
        Habilidade armadilheiro = habilidadeRepository.findByNome("Armadilheiro");
        Habilidade armaduraFiel = habilidadeRepository.findByNome("Armadura Fiel");
        Habilidade arqueria = habilidadeRepository.findByNome("Arqueria");
        Habilidade arqueriadeMestre = habilidadeRepository.findByNome("Arqueria de Mestre");
        Habilidade asasCelestiais = habilidadeRepository.findByNome("Asas Celestiais");
        Habilidade asasFortes = habilidadeRepository.findByNome("Asas Fortes");
        Habilidade asasPesadas = habilidadeRepository.findByNome("Asas Pesadas");
        Habilidade asceta = habilidadeRepository.findByNome("Asceta");
        Habilidade assuntosDiversos = habilidadeRepository.findByNome("Assuntos Diversos");
        Habilidade astuto = habilidadeRepository.findByNome("Astuto");
        Habilidade ataqueAleijador = habilidadeRepository.findByNome("Ataque Aleijador");
        Habilidade ataqueChocante = habilidadeRepository.findByNome("Ataque Chocante");
        Habilidade ataqueCongelante = habilidadeRepository.findByNome("Ataque Congelante");
        Habilidade ataquedoBufalo = habilidadeRepository.findByNome("Ataque do Búfalo");
        Habilidade ataqueEvasivo = habilidadeRepository.findByNome("Ataque Evasivo");
        Habilidade ataqueFantasma = habilidadeRepository.findByNome("Ataque Fantasma");
        Habilidade ataqueFlamejante = habilidadeRepository.findByNome("Ataque Flamejante");
        Habilidade ataqueGiratorio = habilidadeRepository.findByNome("Ataque Giratório");
        Habilidade ataqueRedirecionado = habilidadeRepository.findByNome("Ataque Redirecionado");
        Habilidade ataqueSimultaneo = habilidadeRepository.findByNome("Ataque Simultâneo");
        Habilidade atletismo = habilidadeRepository.findByNome("Atletismo");
        Habilidade atropelar = habilidadeRepository.findByNome("Atropelar");
        Habilidade audacia = habilidadeRepository.findByNome("Audácia");
        Habilidade auradeCura1 = habilidadeRepository.findByNome("Aura de Cura 1");
        Habilidade auradeCura2 = habilidadeRepository.findByNome("Aura de Cura 2");
        Habilidade banir = habilidadeRepository.findByNome("Banir");
        Habilidade barganha = habilidadeRepository.findByNome("Barganha");
        Habilidade bencaodeEllenis = habilidadeRepository.findByNome("Benção de Ellenis");
        Habilidade bencaodeLathellanis = habilidadeRepository.findByNome("Benção de Lathellanis");
        Habilidade berserkir = habilidadeRepository.findByNome("Berserkir");
        Habilidade bestializar = habilidadeRepository.findByNome("Bestializar");
        Habilidade boladeFogo = habilidadeRepository.findByNome("Bola de Fogo");
        Habilidade bonsFrutos = habilidadeRepository.findByNome("Bons Frutos");
        Habilidade bracosExtras1 = habilidadeRepository.findByNome("Braços Extras 1");
        Habilidade bracosExtras2 = habilidadeRepository.findByNome("Braços Extras 2");
        Habilidade bravuraSelvagem1 = habilidadeRepository.findByNome("Bravura Selvagem 1");
        Habilidade bravuraSelvagem2 = habilidadeRepository.findByNome("Bravura Selvagem 2");
        Habilidade brigao = habilidadeRepository.findByNome("Brigão");
        Habilidade cabecaDura = habilidadeRepository.findByNome("Cabeça Dura");
        Habilidade cacadordeCriatura = habilidadeRepository.findByNome("Caçador de [Criatura]");
        Habilidade cacadordeMonstro = habilidadeRepository.findByNome("Caçador de [Monstro]");
        Habilidade caminhadaFantasma = habilidadeRepository.findByNome("Caminhada Fantasma");
        Habilidade caminhadaMagica = habilidadeRepository.findByNome("Caminhada Mágica");
        Habilidade camuflagem = habilidadeRepository.findByNome("Camuflagem");
        Habilidade cancaodaSereia = habilidadeRepository.findByNome("Canção da Sereia");
        Habilidade cancaoDesconcentrante = habilidadeRepository.findByNome("Canção Desconcentrante");
        Habilidade cancaodoRequiem = habilidadeRepository.findByNome("Canção do Réquiem");
        Habilidade cancaodoTriunfo = habilidadeRepository.findByNome("Canção do Triunfo");
        Habilidade cancaoExultante = habilidadeRepository.findByNome("Canção Exultante");
        Habilidade cariatide = habilidadeRepository.findByNome("Cariátide");
        Habilidade cascosAgeis = habilidadeRepository.findByNome("Cascos Ágeis");
        Habilidade cavaleiroExperiente = habilidadeRepository.findByNome("Cavaleiro Experiente");
        Habilidade chamadodoAlfa = habilidadeRepository.findByNome("Chamado do Alfa");
        Habilidade chamasInternas1 = habilidadeRepository.findByNome("Chamas Internas 1");
        Habilidade chamasInternas2 = habilidadeRepository.findByNome("Chamas Internas 2");
        Habilidade chuvadeFlechas = habilidadeRepository.findByNome("Chuva de Flechas");
        Habilidade chuvadeFlechas2 = habilidadeRepository.findByNome("Chuva de Flechas 2");
        Habilidade circulodaProtecao = habilidadeRepository.findByNome("Círculo da Proteção");
        Habilidade codigodaJustica = habilidadeRepository.findByNome("Código da Justiça");
        Habilidade codigodaLealdade = habilidadeRepository.findByNome("Código da Lealdade");
        Habilidade comandoHeroico = habilidadeRepository.findByNome("Comando Heroico");
        Habilidade combatecomDuasArmas1 = habilidadeRepository.findByNome("Combate com Duas Armas 1");
        Habilidade combatecomDuasArmas2 = habilidadeRepository.findByNome("Combate com Duas Armas 2");
        Habilidade combateemGrupo = habilidadeRepository.findByNome("Combate em Grupo");
        Habilidade combateMontado = habilidadeRepository.findByNome("Combate Montado");
        Habilidade combatePesado = habilidadeRepository.findByNome("Combate Pesado");
        Habilidade combateTatico = habilidadeRepository.findByNome("Combate Tático");
        Habilidade companheiroAnimal1 = habilidadeRepository.findByNome("Companheiro Animal 1");
        Habilidade companheiroAnimal2 = habilidadeRepository.findByNome("Companheiro Animal 2");
        Habilidade companheiroAnimal3 = habilidadeRepository.findByNome("Companheiro Animal 3");
        Habilidade companheiroEspiritual = habilidadeRepository.findByNome("Companheiro Espiritual");
        Habilidade comunhaoComEspiritos = habilidadeRepository.findByNome("Comunhão com Espíritos");
        Habilidade congelar = habilidadeRepository.findByNome("Congelar");
        Habilidade conhecimentoArcano = habilidadeRepository.findByNome("Conhecimento Arcano");
        Habilidade conhecimentoMistico = habilidadeRepository.findByNome("Conhecimento Místico");
        Habilidade conjurarAbrigo = habilidadeRepository.findByNome("Conjurar Abrigo");
        Habilidade conjurarArmadosDeuses = habilidadeRepository.findByNome("Conjurar Arma dos Deuses");
        Habilidade conjurarBroquelMistico = habilidadeRepository.findByNome("Conjurar Broquel Místico");
        Habilidade conjurarEscudo = habilidadeRepository.findByNome("Conjurar Escudo");
        Habilidade conjurarFalangedoDestino = habilidadeRepository.findByNome("Conjurar Falange do Destino");
        Habilidade conjurarLancadoDestino = habilidadeRepository.findByNome("Conjurar Lança do Destino");
        Habilidade constituicaoFeerica = habilidadeRepository.findByNome("Constituição Feérica");
        Habilidade contatoComEspiritos = habilidadeRepository.findByNome("Contato com Espíritos");
        Habilidade contatosnoCrime = habilidadeRepository.findByNome("Contatos no Crime");
        Habilidade contosdaEstrada = habilidadeRepository.findByNome("Contos da Estrada");
        Habilidade convocarAnimais = habilidadeRepository.findByNome("Convocar Animais");
        Habilidade coracaodaBatalha = habilidadeRepository.findByNome("Coração da Batalha");
        Habilidade coracaodaMontanha = habilidadeRepository.findByNome("Coração da Montanha");
        Habilidade coracaodaMontanha2 = habilidadeRepository.findByNome("Coração da Montanha 2");
        Habilidade corpoFechado = habilidadeRepository.findByNome("Corpo Fechado");
        Habilidade corpoPesado = habilidadeRepository.findByNome("Corpo Pesado");
        Habilidade corteArterial = habilidadeRepository.findByNome("Corte Arterial");
        Habilidade criarGolem = habilidadeRepository.findByNome("Criar Golem");
        Habilidade curaEspiritual = habilidadeRepository.findByNome("Cura Espiritual");
        Habilidade curarFerimentos1 = habilidadeRepository.findByNome("Curar Ferimentos 1");
        Habilidade curarFerimentos2 = habilidadeRepository.findByNome("Curar Ferimentos 2");
        Habilidade dancaDasEspadas1 = habilidadeRepository.findByNome("Dança das Espadas 1");
        Habilidade dancaDasEspadas2 = habilidadeRepository.findByNome("Dança das Espadas 2");
        Habilidade dancarinoDoAr = habilidadeRepository.findByNome("Dançarino do Ar");
        Habilidade decapitar = habilidadeRepository.findByNome("Decapitar");
        Habilidade defesaAgressiva = habilidadeRepository.findByNome("Defesa Agressiva");
        Habilidade defletor = habilidadeRepository.findByNome("Defletor");
        Habilidade desarmarOponente = habilidadeRepository.findByNome("Desarmar Oponente");
        Habilidade desativarItem = habilidadeRepository.findByNome("Desativar Item");
        Habilidade despertaraFlora = habilidadeRepository.findByNome("Despertar a Flora");
        Habilidade destemor = habilidadeRepository.findByNome("Destemor");
        Habilidade destruicaoElemental = habilidadeRepository.findByNome("Destruição Elemental");
        Habilidade detectarMagia = habilidadeRepository.findByNome("Detectar Magia");
        Habilidade disparoCerteiro = habilidadeRepository.findByNome("Disparo Certeiro");
        Habilidade disparoForte = habilidadeRepository.findByNome("Disparo Forte");
        Habilidade dissiparMagia = habilidadeRepository.findByNome("Dissipar Magia");
        Habilidade diversidade = habilidadeRepository.findByNome("Diversidade");
        Habilidade dogma = habilidadeRepository.findByNome("Dogma");
        Habilidade domdaMagia = habilidadeRepository.findByNome("Dom da Magia");
        Habilidade durocomoPedra = habilidadeRepository.findByNome("Duro como Pedra");
        Habilidade egide = habilidadeRepository.findByNome("Égide");
        Habilidade eletricidadeEstatica = habilidadeRepository.findByNome("Eletricidade Estática");
        Habilidade eletrosfera = habilidadeRepository.findByNome("Eletrosfera");
        Habilidade eloquente = habilidadeRepository.findByNome("Eloquente");
        Habilidade emboscar = habilidadeRepository.findByNome("Emboscar");
        Habilidade empalar = habilidadeRepository.findByNome("Empalar");
        Habilidade enPassant = habilidadeRepository.findByNome("En Passant");
        Habilidade enfeiticarArma1 = habilidadeRepository.findByNome("Enfeitiçar Arma 1");
        Habilidade enfeiticarArma2 = habilidadeRepository.findByNome("Enfeitiçar Arma 2");
        Habilidade enfeiticarArmadura = habilidadeRepository.findByNome("Enfeitiçar Armadura");
        Habilidade entrelacar = habilidadeRepository.findByNome("Entrelaçar");
        Habilidade espiritoAnimal = habilidadeRepository.findByNome("Espírito Animal");
        Habilidade estabilidade = habilidadeRepository.findByNome("Estabilidade");
        Habilidade estracalhar = habilidadeRepository.findByNome("Estraçalhar");
        Habilidade evasao = habilidadeRepository.findByNome("Evasão");
        Habilidade evocarNevasca = habilidadeRepository.findByNome("Evocar Nevasca");
        Habilidade evocarTemporal = habilidadeRepository.findByNome("Evocar Temporal");
        Habilidade exorcismo = habilidadeRepository.findByNome("Exorcismo");
        Habilidade explorarSurpresa = habilidadeRepository.findByNome("Explorar Surpresa");
        Habilidade falhasdaArmadura = habilidadeRepository.findByNome("Falhas da Armadura");
        Habilidade faro = habilidadeRepository.findByNome("Faro");
        Habilidade flanquear = habilidadeRepository.findByNome("Flanquear");
        Habilidade flautadePa = habilidadeRepository.findByNome("Flauta de Pã");
        Habilidade flechasRapidas = habilidadeRepository.findByNome("Flechas Rápidas");
        Habilidade flexivel = habilidadeRepository.findByNome("Flexível");
        Habilidade forcadeExplosao = habilidadeRepository.findByNome("Força de Explosão");
        Habilidade forcaHeroica = habilidadeRepository.findByNome("Força Heróica");
        Habilidade forcaInterior = habilidadeRepository.findByNome("Força Interior");
        Habilidade forjadoAFogo = habilidadeRepository.findByNome("Forjado à Fogo");
        Habilidade formaAnimal1 = habilidadeRepository.findByNome("Forma Animal 1");
        Habilidade formaAnimal2 = habilidadeRepository.findByNome("Forma Animal 2");
        Habilidade formadaRaposa = habilidadeRepository.findByNome("Forma da Raposa");
        Habilidade fortaleza = habilidadeRepository.findByNome("Fortaleza");
        Habilidade frutoRevigorante = habilidadeRepository.findByNome("Fruto Revigorante");
        Habilidade fulgurante = habilidadeRepository.findByNome("Fulgurante");
        Habilidade furiaBestial = habilidadeRepository.findByNome("Fúria Bestial");
        Habilidade furiaDeBatalha = habilidadeRepository.findByNome("Fúria de Batalha");
        Habilidade furtivo = habilidadeRepository.findByNome("Furtivo");
        Habilidade garras = habilidadeRepository.findByNome("Garras");
        Habilidade gatuno = habilidadeRepository.findByNome("Gatuno");
        Habilidade gavinhaseEspinhos = habilidadeRepository.findByNome("Gavinhas e Espinhos");
        Habilidade golpecomEscudo = habilidadeRepository.findByNome("Golpe com Escudo");
        Habilidade golpeDevastador1 = habilidadeRepository.findByNome("Golpe Devastador 1");
        Habilidade golpeDevastador2 = habilidadeRepository.findByNome("Golpe Devastador 2");
        Habilidade golpedoVento = habilidadeRepository.findByNome("Golpe do Vento");
        Habilidade golpesRapidos = habilidadeRepository.findByNome("Golpes Rápidos");
        Habilidade gracaDivina = habilidadeRepository.findByNome("Graça Divina");
        Habilidade gregario = habilidadeRepository.findByNome("Gregário");
        Habilidade gritodeGuerra1 = habilidadeRepository.findByNome("Grito de Guerra 1");
        Habilidade gritodeGuerra2 = habilidadeRepository.findByNome("Grito de Guerra 2");
        Habilidade gritoDeIntimidacao = habilidadeRepository.findByNome("Grito de Intimidação");
        Habilidade gritoEnsurdecedor = habilidadeRepository.findByNome("Grito Ensurdecedor");
        Habilidade gritoEstilhacador = habilidadeRepository.findByNome("Grito Estilhaçador");
        Habilidade guardiaoDaNatureza = habilidadeRepository.findByNome("Guardião da Natureza");
        Habilidade guerreirodeAco1 = habilidadeRepository.findByNome("Guerreiro de Aço 1");
        Habilidade guerreirodeAco2 = habilidadeRepository.findByNome("Guerreiro de Aço 2");
        Habilidade guiaEspiritual = habilidadeRepository.findByNome("Guia Espiritual");
        Habilidade habitantedoDeserto = habilidadeRepository.findByNome("Habitante do Deserto");
        Habilidade herancaFeerica = habilidadeRepository.findByNome("Herança Feérica");
        Habilidade herbalismo = habilidadeRepository.findByNome("Herbalismo");
        Habilidade hierofante = habilidadeRepository.findByNome("Hierofante");
        Habilidade imparavel = habilidadeRepository.findByNome("Imparável");
        Habilidade implacavel = habilidadeRepository.findByNome("Implacável");
        Habilidade improvisacaoLadina = habilidadeRepository.findByNome("Improvisação Ladina");
        Habilidade imunidadeEspiritual = habilidadeRepository.findByNome("Imunidade Espiritual");
        Habilidade incandescer = habilidadeRepository.findByNome("Incandescer");
        Habilidade inferno = habilidadeRepository.findByNome("Inferno");
        Habilidade inflamar = habilidadeRepository.findByNome("Inflamar");
        Habilidade infravisao = habilidadeRepository.findByNome("Infravisão");
        Habilidade integridade = habilidadeRepository.findByNome("Integridade");
        Habilidade intelectoElfico = habilidadeRepository.findByNome("Intelecto Élfico");
        Habilidade inteligenciaHeroica = habilidadeRepository.findByNome("Inteligência Heroica");
        Habilidade investidaForte = habilidadeRepository.findByNome("Investida Forte");
        Habilidade investidaMortal = habilidadeRepository.findByNome("Investida Mortal");
        Habilidade invisibilidadeNatural = habilidadeRepository.findByNome("Invisibilidade Natural");
        Habilidade invocarElemental1 = habilidadeRepository.findByNome("Invocar Elemental 1");
        Habilidade invocarElemental2 = habilidadeRepository.findByNome("Invocar Elemental 2");
        Habilidade invocarElemental3 = habilidadeRepository.findByNome("Invocar Elemental 3");
        Habilidade invocarEspiritoAnimal = habilidadeRepository.findByNome("Invocar Espírito Animal");
        Habilidade isnuu = habilidadeRepository.findByNome("Isnuu");
        Habilidade justicaFinal1 = habilidadeRepository.findByNome("Justiça Final 1");
        Habilidade justicaFinal2 = habilidadeRepository.findByNome("Justiça Final 2");
        Habilidade levitar = habilidadeRepository.findByNome("Levitar");
        Habilidade linguaAfiada = habilidadeRepository.findByNome("Língua Afiada");
        Habilidade luzesdasFadas = habilidadeRepository.findByNome("Luzes das Fadas");
        Habilidade maestriaElemental = habilidadeRepository.findByNome("Maestria Elemental");
        Habilidade malabarista = habilidadeRepository.findByNome("Malabarista");
        Habilidade manterGolem = habilidadeRepository.findByNome("Manter Golem");
        Habilidade mantoCrepitante = habilidadeRepository.findByNome("Manto Crepitante");
        Habilidade marrada = habilidadeRepository.findByNome("Marrada");
        Habilidade matadordeCriatura = habilidadeRepository.findByNome("Matador de [Criatura]");
        Habilidade melodiadaFuria = habilidadeRepository.findByNome("Melodia da Fúria");
        Habilidade melodiaDancante = habilidadeRepository.findByNome("Melodia Dançante");
        Habilidade melodiadoEnjoo = habilidadeRepository.findByNome("Melodia do Enjoo");
        Habilidade melodiadoRepouso = habilidadeRepository.findByNome("Melodia do Repouso");
        Habilidade melodiadosAnimais = habilidadeRepository.findByNome("Melodia dos Animais");
        Habilidade melodiaSonifera = habilidadeRepository.findByNome("Melodia Sonífera");
        Habilidade menteDisciplinada = habilidadeRepository.findByNome("Mente Disciplinada");
        Habilidade menteIluminada = habilidadeRepository.findByNome("Mente Iluminada");
        Habilidade mestredasAdagas1 = habilidadeRepository.findByNome("Mestre das Adagas 1");
        Habilidade mestredasAdagas2 = habilidadeRepository.findByNome("Mestre das Adagas 2");
        Habilidade mestredasAdagas3 = habilidadeRepository.findByNome("Mestre das Adagas 3");
        Habilidade mestredasNotas = habilidadeRepository.findByNome("Mestre das Notas");
        Habilidade mestredeArmas1 = habilidadeRepository.findByNome("Mestre de Armas 1");
        Habilidade mestredeArmas2 = habilidadeRepository.findByNome("Mestre de Armas 2");
        Habilidade mestredeArmas3 = habilidadeRepository.findByNome("Mestre de Armas 3");
        Habilidade mestreDomador = habilidadeRepository.findByNome("Mestre Domador");
        Habilidade mestreEspecialista = habilidadeRepository.findByNome("Mestre Especialista");
        Habilidade montariaEspecial1 = habilidadeRepository.findByNome("Montaria Especial 1");
        Habilidade montariaEspecial2 = habilidadeRepository.findByNome("Montaria Especial 2");
        Habilidade montariaEspecial3 = habilidadeRepository.findByNome("Montaria Especial 3");
        Habilidade mordidaPoderosa = habilidadeRepository.findByNome("Mordida Poderosa");
        Habilidade motivar = habilidadeRepository.findByNome("Motivar");
        Habilidade moverTerra = habilidadeRepository.findByNome("Mover Terra");
        Habilidade movimentoBrusco = habilidadeRepository.findByNome("Movimento Brusco");
        Habilidade movimentosEvasivos = habilidadeRepository.findByNome("Movimentos Evasivos");
        Habilidade nanismo = habilidadeRepository.findByNome("Nanismo");
        Habilidade nascidonasMontanhas = habilidadeRepository.findByNome("Nascido nas Montanhas");
        Habilidade nervosdeAco = habilidadeRepository.findByNome("Nervos de Aço");
        Habilidade nocautear = habilidadeRepository.findByNome("Nocautear");
        Habilidade oDobroouNada = habilidadeRepository.findByNome("O Dobro ou Nada");
        Habilidade olhoDaAguia = habilidadeRepository.findByNome("Olho da Águia");
        Habilidade olhodoFuracao = habilidadeRepository.findByNome("Olho do Furacão");
        Habilidade olhosDeAguia = habilidadeRepository.findByNome("Olhos de águia");
        Habilidade ondadeChamas = habilidadeRepository.findByNome("Onda de Chamas");
        Habilidade ondadeFrio = habilidadeRepository.findByNome("Onda de Frio");
        Habilidade ondadeRaios = habilidadeRepository.findByNome("Onda de Raios");
        Habilidade ondaFantasma = habilidadeRepository.findByNome("Onda Fantasma");
        Habilidade orbeDeContencao = habilidadeRepository.findByNome("Orbe de Contenção");
        Habilidade panache = habilidadeRepository.findByNome("Panache");
        Habilidade paredeDeEscudos = habilidadeRepository.findByNome("Parede de Escudos");
        Habilidade paredeDeGelo = habilidadeRepository.findByNome("Parede de Gelo");
        Habilidade passoLeve = habilidadeRepository.findByNome("Passo Leve");
        Habilidade patasComCascos = habilidadeRepository.findByNome("Patas com Cascos");
        Habilidade patasFortes = habilidadeRepository.findByNome("Patas Fortes");
        Habilidade peleDePedra = habilidadeRepository.findByNome("Pele de Pedra");
        Habilidade peleDePedra2 = habilidadeRepository.findByNome("Pele de Pedra 2");
        Habilidade pernasVulpinas = habilidadeRepository.findByNome("Pernas Vulpinas");
        Habilidade pinturaCorporal = habilidadeRepository.findByNome("Pintura Corporal");
        Habilidade poesiadosBardos = habilidadeRepository.findByNome("Poesia dos Bardos");
        Habilidade pontifice = habilidadeRepository.findByNome("Pontífice");
        Habilidade portal = habilidadeRepository.findByNome("Portal");
        Habilidade potencia = habilidadeRepository.findByNome("Potência");
        Habilidade precisao = habilidadeRepository.findByNome("Precisão");
        Habilidade presencaReal = habilidadeRepository.findByNome("Presença Real");
        Habilidade primaz = habilidadeRepository.findByNome("Primaz");
        Habilidade principioNatural = habilidadeRepository.findByNome("Princípio Natural");
        Habilidade prisaodeGelo = habilidadeRepository.findByNome("Prisão de Gelo");
        Habilidade protecaoMistica = habilidadeRepository.findByNome("Proteção Mística");
        Habilidade punhodePedra = habilidadeRepository.findByNome("Punho de Pedra");
        Habilidade purgar = habilidadeRepository.findByNome("Purgar");
        Habilidade racaFlorestal = habilidadeRepository.findByNome("Raça Florestal");
        Habilidade racaSubterranea = habilidadeRepository.findByNome("Raça Subterrânea");
        Habilidade rajadadeAgua = habilidadeRepository.findByNome("Rajada de Água");
        Habilidade rajadadeEspinhos = habilidadeRepository.findByNome("Rajada de Espinhos");
        Habilidade rajadadeGelo = habilidadeRepository.findByNome("Rajada de Gelo");
        Habilidade rajadaElemental = habilidadeRepository.findByNome("Rajada Elemental");
        Habilidade recursos = habilidadeRepository.findByNome("Recursos");
        Habilidade relampago1 = habilidadeRepository.findByNome("Relâmpago 1");
        Habilidade relampago2 = habilidadeRepository.findByNome("Relâmpago 2");
        Habilidade resistenciaElemental = habilidadeRepository.findByNome("Resistência Elemental");
        Habilidade retalhar = habilidadeRepository.findByNome("Retalhar");
        Habilidade retesarEficiente = habilidadeRepository.findByNome("Retesar Eficiente");
        Habilidade ripostar = habilidadeRepository.findByNome("Ripostar");
        Habilidade robustez = habilidadeRepository.findByNome("Robustez");
        Habilidade rugidodeAhogr = habilidadeRepository.findByNome("Rugido de Ahogr");
        Habilidade rugidodoAlfa = habilidadeRepository.findByNome("Rugido do Alfa");
        Habilidade rugidodoPredador = habilidadeRepository.findByNome("Rugido do Predador");
        Habilidade sabedoriaSelvagem = habilidadeRepository.findByNome("Sabedoria Selvagem");
        Habilidade semEscapatoria = habilidadeRepository.findByNome("Sem Escapatória");
        Habilidade senhordasLaminas = habilidadeRepository.findByNome("Senhor das Lâminas");
        Habilidade sentidosApurados = habilidadeRepository.findByNome("Sentidos Apurados");
        Habilidade sentidosDeCacador = habilidadeRepository.findByNome("Sentidos de Caçador");
        Habilidade soproDeFogo = habilidadeRepository.findByNome("Sopro de Fogo");
        Habilidade sorte = habilidadeRepository.findByNome("Sorte");
        Habilidade telecinesia = habilidadeRepository.findByNome("Telecinésia");
        Habilidade teleporte1 = habilidadeRepository.findByNome("Teleporte 1");
        Habilidade teleporte2 = habilidadeRepository.findByNome("Teleporte 2");
        Habilidade tempestadedeGelo = habilidadeRepository.findByNome("Tempestade de Gelo");
        Habilidade tempestadeDeLaminas = habilidadeRepository.findByNome("Tempestade de Lâminas");
        Habilidade toqueMistico = habilidadeRepository.findByNome("Toque Místico");
        Habilidade touche = habilidadeRepository.findByNome("Touché");
        Habilidade transpor = habilidadeRepository.findByNome("Transpor");
        Habilidade trapaceiroImpecavel = habilidadeRepository.findByNome("Trapaceiro Impecável");
        Habilidade truqueSujo = habilidadeRepository.findByNome("Truque Sujo");
        Habilidade turbilhao = habilidadeRepository.findByNome("Turbilhão");
        Habilidade ulfhednar = habilidadeRepository.findByNome("Ulfhednar");
        Habilidade valordaVitoria = habilidadeRepository.findByNome("Valor da Vitória");
        Habilidade vantagemAnimal1 = habilidadeRepository.findByNome("Vantagem Animal 1");
        Habilidade vantagemAnimal2 = habilidadeRepository.findByNome("Vantagem Animal 2");
        Habilidade velocidade = habilidadeRepository.findByNome("Velocidade");
        Habilidade veneficio = habilidadeRepository.findByNome("Venefício");
        Habilidade vigordoDeserto = habilidadeRepository.findByNome("Vigor do Deserto");
        Habilidade vigorNordico = habilidadeRepository.findByNome("Vigor Nórdico");
        Habilidade virtuoso = habilidadeRepository.findByNome("Virtuoso");
        Habilidade visaoAuditiva = habilidadeRepository.findByNome("Visão Auditiva");
        Habilidade voadorEximio = habilidadeRepository.findByNome("Voador Exímio");
        Habilidade vocalista = habilidadeRepository.findByNome("Vocalista");
        Habilidade vontadeDeFerro = habilidadeRepository.findByNome("Vontade de Ferro");
        Habilidade vontadeHeroica = habilidadeRepository.findByNome("Vontade Heróica");

        // Todas as classes
        List<Classe> todasClasses = new ArrayList<>();
        todasClasses.add(guerreiro);
        todasClasses.add(patrulheiro);
        todasClasses.add(feiticeiro);
        todasClasses.add(ladino);
        todasClasses.add(bardo);
        todasClasses.add(druida);
        todasClasses.add(espadachim);
        todasClasses.add(paladino);
        todasClasses.add(runico);
        todasClasses.add(sacerdote);
        todasClasses.add(xama);

        for (Classe classe: todasClasses) {
            habilidadeClasseRepository.save(new HabilidadeClasse(agilidadeHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(atletismo, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(forcaHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(forcaInterior, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(inteligenciaHeroica, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(nanismo, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(nervosdeAco, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(recursos, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(vontadeDeFerro, classe, false));
            habilidadeClasseRepository.save(new HabilidadeClasse(vontadeHeroica, classe, false));
        }

        // Xamãs
        habilidadeClasseRepository.save(new HabilidadeClasse(bravuraSelvagem1, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(contatoComEspiritos, xama, false));
        habilidadeClasseRepository.save(new HabilidadeClasse(comunhaoComEspiritos, xama, false));

        return "";
    }
}
